
import 'package:quick_ecommerce_city_panel_redefined/View/DisputeHubDir/dispute_model.dart';

List<DisputeItem> demoDisputes = [
  DisputeItem(
    id: 1,
    type: DisputeType.defective,
    product: 'Premium Wireless Earbuds',
    hub: 'Hub Central - Delhi',
    sku: 'SKU-WE-001',
    category: 'Electronics',
    transferred: 120,
    defective: 8,
    missing: 0,
    variants: [
      VariantRow(name: 'Black / 1 unit', sent: 40, received: 40, defective: 3, missing: 0),
      VariantRow(name: 'White / 1 unit', sent: 40, received: 38, defective: 3, missing: 2),
      VariantRow(name: 'Blue / 1 unit', sent: 40, received: 40, defective: 2, missing: 0),
    ],
    note: 'Units arrived with broken charging case hinge. Multiple variants affected.',
    status: DisputeStatus.open,
    date: 'Apr 09, 2026',
    severity: DisputeSeverity.high,
  ),
  DisputeItem(
    id: 2,
    type: DisputeType.missing,
    product: 'Cotton Slim-Fit Shirts',
    hub: 'Hub West - Mumbai',
    sku: 'SKU-CS-045',
    category: 'Apparel',
    transferred: 200,
    defective: 0,
    missing: 15,
    variants: [
      VariantRow(name: 'M / Blue', sent: 60, received: 55, defective: 0, missing: 5),
      VariantRow(name: 'L / Blue', sent: 70, received: 66, defective: 0, missing: 4),
      VariantRow(name: 'XL / Blue', sent: 70, received: 64, defective: 0, missing: 6),
    ],
    note: '15 units not found in delivery. Packing slip shows 200 but physical count is 185.',
    status: DisputeStatus.underReview,
    date: 'Apr 08, 2026',
    severity: DisputeSeverity.medium,
  ),
  DisputeItem(
    id: 3,
    type: DisputeType.defective,
    product: 'Stainless Steel Water Bottle',
    hub: 'Hub South - Bengaluru',
    sku: 'SKU-WB-012',
    category: 'Kitchenware',
    transferred: 80,
    defective: 12,
    missing: 0,
    variants: [
      VariantRow(name: '500ml / Silver', sent: 40, received: 40, defective: 7, missing: 0),
      VariantRow(name: '750ml / Silver', sent: 40, received: 40, defective: 5, missing: 0),
    ],
    note: 'Lid seal is defective — leaks when tilted. Entire batch may be from faulty mold.',
    status: DisputeStatus.sentToCity,
    date: 'Apr 07, 2026',
    severity: DisputeSeverity.high,
  ),
  DisputeItem(
    id: 4,
    type: DisputeType.missing,
    product: 'Yoga Mat Premium',
    hub: 'Hub North - Chandigarh',
    sku: 'SKU-YM-007',
    category: 'Sports',
    transferred: 60,
    defective: 0,
    missing: 4,
    variants: [
      VariantRow(name: '6mm / Purple', sent: 30, received: 28, defective: 0, missing: 2),
      VariantRow(name: '6mm / Green', sent: 30, received: 28, defective: 0, missing: 2),
    ],
    note: '4 units missing from shipment. Transit damage suspected.',
    status: DisputeStatus.open,
    date: 'Apr 07, 2026',
    severity: DisputeSeverity.low,
  ),
  DisputeItem(
    id: 5,
    type: DisputeType.defective,
    product: 'Bluetooth Smart Speaker',
    hub: 'Hub East - Kolkata',
    sku: 'SKU-BS-033',
    category: 'Electronics',
    transferred: 50,
    defective: 6,
    missing: 0,
    variants: [
      VariantRow(name: 'Black / Mini', sent: 25, received: 25, defective: 4, missing: 0),
      VariantRow(name: 'Gray / Mini', sent: 25, received: 25, defective: 2, missing: 0),
    ],
    note: 'Speaker emits static noise at mid-volume. Affects both color variants.',
    status: DisputeStatus.open,
    date: 'Apr 06, 2026',
    severity: DisputeSeverity.high,
  ),
  DisputeItem(
    id: 6,
    type: DisputeType.pending,
    product: 'Running Shoes - AirStride',
    hub: 'Hub Central - Delhi',
    sku: 'SKU-RS-022',
    category: 'Footwear',
    transferred: 100,
    defective: 3,
    missing: 2,
    variants: [
      VariantRow(name: 'Size 8 / Black', sent: 35, received: 33, defective: 1, missing: 1),
      VariantRow(name: 'Size 9 / Black', sent: 35, received: 34, defective: 1, missing: 0),
      VariantRow(name: 'Size 10 / Black', sent: 30, received: 29, defective: 1, missing: 1),
    ],
    note: 'Some units have sole detachment. Pending quality check by city panel.',
    status: DisputeStatus.pendingReview,
    date: 'Apr 05, 2026',
    severity: DisputeSeverity.medium,
  ),
  DisputeItem(
    id: 7,
    type: DisputeType.missing,
    product: 'Ceramic Coffee Mug Set',
    hub: 'Hub West - Mumbai',
    sku: 'SKU-CM-089',
    category: 'Kitchenware',
    transferred: 150,
    defective: 0,
    missing: 9,
    variants: [
      VariantRow(name: '4-pc / White', sent: 75, received: 70, defective: 0, missing: 5),
      VariantRow(name: '4-pc / Black', sent: 75, received: 71, defective: 0, missing: 4),
    ],
    note: '9 units missing. Outer carton showed signs of transit tampering.',
    status: DisputeStatus.underReview,
    date: 'Apr 04, 2026',
    severity: DisputeSeverity.medium,
  ),
  DisputeItem(
    id: 8,
    type: DisputeType.defective,
    product: 'Kids Wooden Blocks Set',
    hub: 'Hub South - Bengaluru',
    sku: 'SKU-KB-056',
    category: 'Toys',
    transferred: 90,
    defective: 14,
    missing: 0,
    variants: [
      VariantRow(name: '30-pc / Mixed', sent: 50, received: 50, defective: 8, missing: 0),
      VariantRow(name: '50-pc / Mixed', sent: 40, received: 40, defective: 6, missing: 0),
    ],
    note: 'Paint chipping on multiple blocks. Safety concern — not child-safe.',
    status: DisputeStatus.sentToCity,
    date: 'Apr 03, 2026',
    severity: DisputeSeverity.high,
  ),
  DisputeItem(
    id: 9,
    type: DisputeType.pending,
    product: 'Face Serum - Vitamin C',
    hub: 'Hub North - Chandigarh',
    sku: 'SKU-FS-201',
    category: 'Beauty',
    transferred: 200,
    defective: 5,
    missing: 3,
    variants: [
      VariantRow(name: '30ml / Regular', sent: 100, received: 97, defective: 3, missing: 0),
      VariantRow(name: '50ml / Regular', sent: 100, received: 97, defective: 2, missing: 3),
    ],
    note: 'Serum discoloration noticed in 30ml variant. Pending lab verification.',
    status: DisputeStatus.pendingReview,
    date: 'Apr 02, 2026',
    severity: DisputeSeverity.medium,
  ),
];