// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDcMvkuu8Iuh9WnL05ZnH6HEXxXMJjVMIw',
    appId: '1:630416157668:web:b01bc35c1ba7de1a72b5f1',
    messagingSenderId: '630416157668',
    projectId: 'fasto-2b9c5',
    authDomain: 'fasto-2b9c5.firebaseapp.com',
    storageBucket: 'fasto-2b9c5.firebasestorage.app',
    measurementId: 'G-C3K5RJP2NC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCNqFrHJn1DnqRYnYDWufjweIWPcTdBzpg',
    appId: '1:630416157668:android:06125476a08f752e72b5f1',
    messagingSenderId: '630416157668',
    projectId: 'fasto-2b9c5',
    storageBucket: 'fasto-2b9c5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD-yNjDaPYZj2VSqkkzwSlammK13UT_Rsc',
    appId: '1:630416157668:ios:da68209f347ff30c72b5f1',
    messagingSenderId: '630416157668',
    projectId: 'fasto-2b9c5',
    storageBucket: 'fasto-2b9c5.firebasestorage.app',
    iosBundleId: 'com.fc.quickEcommerceCityPanelRedefined',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD-yNjDaPYZj2VSqkkzwSlammK13UT_Rsc',
    appId: '1:630416157668:ios:da68209f347ff30c72b5f1',
    messagingSenderId: '630416157668',
    projectId: 'fasto-2b9c5',
    storageBucket: 'fasto-2b9c5.firebasestorage.app',
    iosBundleId: 'com.fc.quickEcommerceCityPanelRedefined',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDcMvkuu8Iuh9WnL05ZnH6HEXxXMJjVMIw',
    appId: '1:630416157668:web:279115a8f82177a772b5f1',
    messagingSenderId: '630416157668',
    projectId: 'fasto-2b9c5',
    authDomain: 'fasto-2b9c5.firebaseapp.com',
    storageBucket: 'fasto-2b9c5.firebasestorage.app',
    measurementId: 'G-WBFZ5Z2MV0',
  );
}
